layout_spectrum: 0.7724015
color:
  saturation: 0.2069718
  lightness: 0.1742065
  brandStrength: 0.2293907
  brandColors:
    - '#FFFFFF'
    - '#7D7E7F'
    - '#414342'
    - '#0070AD'
    - '#BDBEBD'
  rhythmicContrast: 0.1603111
typography_spectrum: 0.3793802
name: Spinetrainer
